# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

warnings_are_errors: false

r_packages:
  - ncdf4
  - V8
  - ForestTools
  
bioc_packages:
  - BiocGenerics
  - Biobase
  
r_github_packages:
  - r-spatial/link2GI
  
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - saga 
      - grass
      - otb-bin
      - netcdf-bin 
      - libv8-3.14-dev