# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r		 
r:
  - release
  - oldrel

r_packages:
  - covr
  - stringr
  - foreach
  - sp
  - sf
  - htmlwidgets
  - htmltools
  - Rcpp
  - rgdal
  - rgeos
  - gdalUtils
  - geosphere
  - tools
  - maptools
  - mapview
  - log4r
  - caret
  - igraph
  - zoo
  - data.table
  - parallel
  - spatial.tools
  - velox
  - link2GI
  - doParallel
  - CAST
  - curl
  - glcm
  - inline
  - raster
  - lattice
  - latticeExtra
  - crayon

sudo: required

dist: trusty

addons:
  postgresql: "9.6"


before_install:

  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y  libmagick++-dev gimp inkscape grsync arandr gparted filezilla 
  - sudo apt-get install -y  git-core cvs subversion mercurial aptitude
  - sudo apt-get install -y  git cmake g++ libboost-all-dev libgdal1-dev libeigen3-dev libflann-dev libopenni-dev 
  - sudo apt-get install -y  lupin-casper casper
  - sudo apt-get install -y  liblvm2app2.2 liblvm2cmd2.02 liblzo2-2  libreadline5  libtimezonemap1 
  - sudo apt-get install -y  wamerican xfsprogs feh libid3tag0 libimlib2 ecryptfs-utils libecryptfs0 libnss3-1d
  - sudo apt-get install -y  libdebian-installer4 libgif4 sbsigntool libjpeg-progs libjpeg8
  - sudo apt-get install -y  build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl    
  - sudo apt-get install -y  idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script 
  - sudo apt-get install -y  libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev
  - sudo apt-get install -y  python2.7 python-dev build-essential python-shapely python-rpy python-gdal python-psycopg2 python-rpy2 
  - sudo apt-get install -y  python-numpy python-wxtools spyder python-setuptools-doc python-vtk libvtk-java python-numpy libgeotiff-dev     
  - sudo apt-get install -y  swig2.0 python-scipy python-pip python-wheel libgeos++-dev python-software-properties
  - sudo apt-get install -y  libgdal1-dev binutils libproj-dev gdal-bin geotiff-bin
  - sudo apt-get install -y  r-base rstudio-upstream-deb r-cran-rjava libvtk5.8-qt4 libqhull-dev qt-sdk libvtk5-qt4-dev libpcap-dev 
  - sudo apt-get install -y  python-vtk libvtk-java python-numpy libgeotiff-dev libgeos++-dev libcurl4-openssl-dev
  - sudo apt-get install -y  libwxgtk3.0-dev libgdal-dev libproj-dev libjasper-dev libexpat1-dev wx-common libexpat1-dev libogdi3.2-dev 
  - sudo apt-get install -y  unixodbc-dev libssl-dev libffi-dev python-dev libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev
  - sudo apt-get install -y  libevent-dev liblas-bin liblas-dev 
  - sudo apt-get install -y  libimage-exiftool-perl dcraw gpsbabel
  - sudo apt-get install -y  grass saga qgis qgis-api-doc qgis-plugin-globe-common qgis-common qgis-providers-common 
  - sudo apt-get install -y  qgis-provider-grass python-qgis 
  - sudo apt-get install -y  libgd-gd2-perl libv8-3.14-dev usb-creator-gtk

  # install tmap dependencies
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev
  # install tmap dependencies; for 16.04 libjq-dev this ppa is needed:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libjq-dev
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies:
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
  # postgis source compile dependencies:
  - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
  # install postgis from source:
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  # create postgis databases:
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"

warnings_are_errors: false

after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  
  - Rscript -e 'library(covr); codecov()'

