# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: required
warnings_are_errors: false
bundler_args: --retry 7



bioc_packages:
  - BiocGenerics
  - Biobase

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - saga 
      - grass
      - otb-bin
      - libnetcdff-dev
      - netcdf-bin 



env:
  global:
    - DEPENDS="numpy>=1.9.0 cython>=0.21 setuptools>=18.0 cftime"
    - NO_NET=1
    - MPI=0

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
  allow_failures:
    - python: "3.8-dev"
  include:
    # Absolute minimum dependencies.
    - python: 2.7
      env:
        - DEPENDS="numpy==1.9.0 cython==0.21 ordereddict==1.1 setuptools==18.0 cftime"
    # test MPI
    - python: 2.7
      dist: trusty
      env: 
        - MPI=1
        - CC=mpicc
        - DEPENDS="numpy>=1.9.0 cython>=0.21 setuptools>=18.0 mpi4py>=1.3.1 cftime"
        - NETCDF_VERSION=4.6.1
        - NETCDF_DIR=$HOME
        - PATH=${NETCDF_DIR}/bin:${PATH} # pick up nc-config here
      addons:
        apt:
          packages:
            - openmpi-bin
            - libopenmpi-dev
            - libhdf5-openmpi-dev


r_github_packages:
  - r-spatial/link2GI
  
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

dist: trusty

addons:
  postgresql: "9.6"

before_install:
  - export PATH=${NETCDF_DIR}/bin:${PATH} 
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # install tmap dependencies
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev
  # install tmap dependencies; for 16.04 libjq-dev this ppa is needed:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libjq-dev
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies:
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
  # postgis source compile dependencies:
  - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
  # install postgis from source:
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  # create postgis databases:
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"

before_script:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  
after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"