# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: required
warnings_are_errors: false

r_packages:
  - ncdf4
  - V8
  - ForestTools
  
r_github_packages:
  - r-spatial/link2GI
  
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - saga 
      - grass
      - otb-bin
      - libnetcdf-dev
      - libgeos-dev
      - libproj-dev
      - libgdal-dev
      - netcdf-bin 
      - libudunits2-dev
      - libv8-3.14-dev