# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
warnings_are_errors: false
bundler_args: --retry 7

bioc_packages:
  - BiocGenerics
  - Biobase

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - saga 
      - grass
      - otb-bin
      - netcdf-bin 
