# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: required
warnings_are_errors: false

r_packages:
-lidR  

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"


before_install:

  - sudo sh -c 'echo "deb http://qgis.org/ubuntugis trusty main" >> /etc/apt/sources.list'
  - sudo sh -c 'echo "deb-src http://qgis.org/ubuntugis trusty main " >> /etc/apt/sources.list'
  - wget -O - http://qgis.org/downloads/qgis-2017.gpg.key | gpg --import
  - gpg --fingerprint CAEB3DC3BDF7FB45 && gpg --export --armor CAEB3DC3BDF7FB45 | sudo apt-key add -
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable  
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y  gdal-bin libgdal-dev python-gdal python3-gdal libudunits2-dev saga
  - sudo apt-get install -y  libdebian-installer4 libgif4 sbsigntool libjpeg-progs libjpeg8
  - sudo apt-get install -y  build-essential autoconf libtool pkg-config 
  - sudo apt-get install -y  libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev
  - sudo apt-get install -y  libgdal1-dev binutils libproj-dev gdal-bin geotiff-bin
  - sudo apt-get install -y  r-base  libxslt1-dev zlib1g-dev
  - sudo apt-get install -y  libevent-dev liblas-bin liblas-dev 
  - sudo apt-get install -y  libimage-exiftool-perl dcraw gpsbabel
  - sudo apt-get install -y  grass  
  - sudo apt-get install -y   
  - sudo apt-get install -y  libgd-gd2-perl libv8-3.14-dev 

  # install tmap dependencies
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev
  # install tmap dependencies; for 16.04 libjq-dev this ppa is needed:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libjq-dev
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies:
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
before_script:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  
  - sleep 3 # give xvfb some time to start
  
  

 

