# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
cache: packages
  
#- oldrel # breaks on lacking isFALSE#/isTRUE


addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - saga 
      - grass
      - otb-bin